---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: registry.fedoraproject.org/fedora:latest
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
    ssh_connection:
      pipelining: false
  log: true
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
...
